// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/infra/grpc/protofiles/order.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81083cb550ac9a5, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CreateOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Tax                  float32  `protobuf:"fixed32,3,opt,name=tax,proto3" json:"tax,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81083cb550ac9a5, []int{1}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateOrderRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreateOrderRequest) GetTax() float32 {
	if m != nil {
		return m.Tax
	}
	return 0
}

type OrderResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Tax                  float32  `protobuf:"fixed32,3,opt,name=tax,proto3" json:"tax,omitempty"`
	FinalPrice           float32  `protobuf:"fixed32,4,opt,name=final_price,json=finalPrice,proto3" json:"final_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81083cb550ac9a5, []int{2}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderResponse) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderResponse) GetTax() float32 {
	if m != nil {
		return m.Tax
	}
	return 0
}

func (m *OrderResponse) GetFinalPrice() float32 {
	if m != nil {
		return m.FinalPrice
	}
	return 0
}

type CreateOrderResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Tax                  float32  `protobuf:"fixed32,3,opt,name=tax,proto3" json:"tax,omitempty"`
	FinalPrice           float32  `protobuf:"fixed32,4,opt,name=final_price,json=finalPrice,proto3" json:"final_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81083cb550ac9a5, []int{3}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateOrderResponse) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreateOrderResponse) GetTax() float32 {
	if m != nil {
		return m.Tax
	}
	return 0
}

func (m *CreateOrderResponse) GetFinalPrice() float32 {
	if m != nil {
		return m.FinalPrice
	}
	return 0
}

type ListOrdersResponse struct {
	Orders               []*OrderResponse `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListOrdersResponse) Reset()         { *m = ListOrdersResponse{} }
func (m *ListOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*ListOrdersResponse) ProtoMessage()    {}
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81083cb550ac9a5, []int{4}
}

func (m *ListOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrdersResponse.Unmarshal(m, b)
}
func (m *ListOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrdersResponse.Marshal(b, m, deterministic)
}
func (m *ListOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrdersResponse.Merge(m, src)
}
func (m *ListOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_ListOrdersResponse.Size(m)
}
func (m *ListOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrdersResponse proto.InternalMessageInfo

func (m *ListOrdersResponse) GetOrders() []*OrderResponse {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*CreateOrderRequest)(nil), "pb.CreateOrderRequest")
	proto.RegisterType((*OrderResponse)(nil), "pb.OrderResponse")
	proto.RegisterType((*CreateOrderResponse)(nil), "pb.CreateOrderResponse")
	proto.RegisterType((*ListOrdersResponse)(nil), "pb.ListOrdersResponse")
}

func init() {
	proto.RegisterFile("internal/infra/grpc/protofiles/order.proto", fileDescriptor_a81083cb550ac9a5)
}

var fileDescriptor_a81083cb550ac9a5 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0xa5, 0xad, 0xbb, 0xb2, 0x53, 0x15, 0x8d, 0xb2, 0x96, 0xbd, 0x58, 0x7a, 0xaa, 0x1e, 0x1a,
	0x58, 0xef, 0x0a, 0x8a, 0xb7, 0x05, 0xa5, 0xde, 0xbc, 0x48, 0xba, 0x9d, 0x6a, 0xa0, 0xa6, 0x31,
	0x89, 0xa2, 0x27, 0x7f, 0x5d, 0x32, 0x5b, 0xd4, 0xa5, 0x9e, 0x04, 0x6f, 0xc9, 0x9b, 0x97, 0xf7,
	0x5e, 0x66, 0x06, 0x4e, 0xa4, 0x72, 0x68, 0x94, 0x68, 0xb9, 0x54, 0x8d, 0x11, 0xfc, 0xc1, 0xe8,
	0x25, 0xd7, 0xa6, 0x73, 0x5d, 0x23, 0x5b, 0xb4, 0xbc, 0x33, 0x35, 0x9a, 0x82, 0x00, 0x16, 0xea,
	0x2a, 0xdb, 0x84, 0xd1, 0xd5, 0x93, 0x76, 0xef, 0xd9, 0x02, 0xd8, 0xa5, 0x41, 0xe1, 0xf0, 0xda,
	0x33, 0x4a, 0x7c, 0x7e, 0x41, 0xeb, 0xd8, 0x0e, 0x84, 0xb2, 0x4e, 0x82, 0x34, 0xc8, 0x27, 0x65,
	0x28, 0x6b, 0x76, 0x00, 0x23, 0x6d, 0xe4, 0x12, 0x93, 0x30, 0x0d, 0xf2, 0xb0, 0x5c, 0x5d, 0xd8,
	0x2e, 0x44, 0x4e, 0xbc, 0x25, 0x11, 0x61, 0xfe, 0x98, 0x3d, 0xc2, 0x76, 0xaf, 0x63, 0x75, 0xa7,
	0x2c, 0xfe, 0x55, 0x88, 0x1d, 0x41, 0xdc, 0x48, 0x25, 0xda, 0xfb, 0x15, 0x7b, 0x83, 0x2a, 0x40,
	0xd0, 0x8d, 0x47, 0x32, 0x05, 0xfb, 0x6b, 0xb9, 0xff, 0xdb, 0xef, 0x1c, 0xd8, 0x42, 0x5a, 0x47,
	0x6e, 0xf6, 0xcb, 0xee, 0x18, 0xc6, 0xd4, 0x59, 0x9b, 0x04, 0x69, 0x94, 0xc7, 0xf3, 0xbd, 0x42,
	0x57, 0xc5, 0x5a, 0xa2, 0xb2, 0x27, 0xcc, 0x3f, 0x60, 0x8b, 0x0a, 0xb7, 0x68, 0x5e, 0x7d, 0x86,
	0x33, 0x88, 0x7f, 0x7c, 0x80, 0x4d, 0xfd, 0xcb, 0xe1, 0x24, 0x66, 0x87, 0x03, 0xbc, 0xb7, 0xe6,
	0x00, 0xdf, 0x81, 0xd8, 0xc4, 0xd3, 0x68, 0xa2, 0x33, 0x52, 0x1a, 0x66, 0xbd, 0x48, 0xee, 0xa6,
	0xbf, 0x2e, 0x49, 0x55, 0x8d, 0x69, 0x2f, 0x4e, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xe8,
	0x0c, 0x43, 0x45, 0x02, 0x00, 0x00,
}
